services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb_container
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - mariadb_vol:/var/lib/mysql

volumes:
  mariadb_vol:
